PACKAGE_NAME="hyperpixel2r-kms"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="hyperpixel2r_kms"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
CLEAN="make clean"
MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=/lib/modules/${kernelver}/build modules"
